require 'base64'

def pshcmd(cmd)
    encoded_cmd = Base64.strict_encode64(cmd.encode('utf-16le'))
    result = `powershell.exe -encodedCommand #{encoded_cmd}`.chomp
    return result
end

switch_name = pshcmd("Get-VMSwitch | Select-Object Name | findstr Default")
switch_ip = pshcmd("(Get-NetIPAddress -InterfaceAlias \"vEthernet (#{switch_name})\" -AddressFamily IPV4).IPAddress")
host_list = [
  {
    :name => "TestNode",
    :box => "generic/ubuntu1804",
    :hostname => "TestNode",
  } 
]

Vagrant.configure("2") do |config|
  config.vm.provider "hyperv"

  host_list.each do |item|
    config.vm.define item[:name]  do |host|
      host.vm.box=item[:box]
      host.vm.hostname=item[:hostname]
      # host.vm.provision:shell, privileged:false, path:"../ubuntu/script/reset.sh"
      host.vm.network:public_network, bridge: "#{switch_name}"
    end
  end
end
