host_list = [
  {
    :name => "host1",
    :box => "generic/centos7",
    :hostname => "host1",
  },
  {
    :name => "host2",
    :box => "generic/centos7",
    :hostname => "host2",
  },
  {
    :name => "host3",
    :box => "generic/centos7",
    :hostname => "host3",
  },
   {
    :name => "host4",
    :box => "generic/centos7",
    :hostname => "host4",
  } 
]

Vagrant.configure("2") do |config|
  host_list.each do |item|
    config.vm.define item[:name]  do |host|
      host.vm.box=item[:box]
      host.vm.hostname=item[:hostname]
      host.vm.provision "shell", path: "reset/start.sh"
      host.vm.network "public_network"
    end
  end
end
