host_list = [
  {
    :name => "centos",
    :box => "centos",
    :hostname => "centos-vm",
    :ipaddr => "192.168.2.82",
    :bridge => "enp8s0"
  },
]
Vagrant.configure("2") do |config|
  host_list.each do |item|
    config.vm.define item[:name]  do |host|
      host.vm.box=item[:box]
      host.vm.hostname=item[:hostname]
      host.vm.provision "shell", path: "reset/start.sh"
      host.vm.network "public_network",ip: item[:ipaddr],bridge: item[:bridge]
    end
  end
end