require 'base64'

def pshcmd(cmd)
  encoded_cmd = Base64.strict_encode64(cmd.encode('utf-16le'))
  `powershell.exe -encodedCommand #{encoded_cmd}`.chomp
end

vm_provider = 'hyperv'
switch_name = pshcmd('Get-VMSwitch | Select-Object Name | findstr Default')
switch_ip = pshcmd("(Get-NetIPAddress -InterfaceAlias \"vEthernet (#{switch_name})\" -AddressFamily IPV4).IPAddress")

host_list = [
  {
    name: 'master',
    hostname: 'master',
    mem: 4096,
    maxmem: 4096
  },
  {
    name: 'worker1',
    hostname: 'worker1'
  },
  {
    name: 'worker2',
    hostname: 'worker2'
  }
]

# Vagrant
Vagrant.configure('2') do |config|
  if Vagrant.has_plugin?('vagrant-proxyconf')
    config.proxy.http     = "http://#{switch_ip}:7890/"
    config.proxy.https    = "http://#{switch_ip}:7890/"
    config.proxy.no_proxy = 'localhost,127.0.0.1,.example.com'
  end

  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
  end

  config.vm.box = 'generic/ubuntu1804'
  config.vm.provider "#{vm_provider}"
  config.vm.network 'public_network', bridge: "#{switch_name}"

  host_list.each do |item|
    config.vm.define item[:name] do |host|
      host.vm.hostname = item[:hostname]

      if item.key?(:mem)
        host.vm.provider "#{vm_provider}" do |hv|
          hv.memory = item[:mem]
          hv.maxmemory = item[:maxmem]
        end
      end

      host.vm.provision 'shell', path: 'script/master.sh', privileged: false if host.vm.hostname == 'master'
    end
  end
end
