host_list = [
  {
    :name => "host1",
    :box => "generic/ubuntu2204",
    :hostname => "host1",
    :ipaddr => "172.27.10.101"
  },
  {
    :name => "host2",
    :box => "generic/ubuntu2204",
    :hostname => "host2",
    :ipaddr => "172.27.10.102"
  },
  {
    :name => "host3",
    :box => "generic/ubuntu2204",
    :hostname => "host3",
    :ipaddr => "172.27.10.103"
  },
   {
    :name => "host4",
    :box => "generic/ubuntu2204",
    :hostname => "host4",
    :ipaddr => "172.27.10.104"
  }, 
  {
    :name => "host5",
    :box => "generic/ubuntu2204",
    :hostname => "host5",
    :ipaddr => "172.27.10.105"
  } 
]

Vagrant.configure("2") do |config|
  host_list.each do |item|
    config.vm.define item[:name]  do |host|
      host.vm.box=item[:box]
      host.vm.hostname=item[:hostname]
      host.vm.provision "shell", path: "script/reset.sh", privileged: false
      host.vm.network "public_network", ip: item[:ipaddr], bridge:"Hyper-V Virtual Ethernet Adapter #2"
    end
  end
end
